# run: conda env create --file environment.yml
name: attention_tsp
channels:
- pytorch
- anaconda
- conda-forge
- defaults
dependencies:
- python>=3.6
- pip
- anaconda
- tqdm
- cuda91
- pip:
  - tensorboard_logger
  - pytorch
  - torch
  - torchvision